### ISSUE TITLE
Forgotten Wenches Invis Armor Bug

### ISSUE THREAD

**Issue by erri120** [erri120/lotus#1]
Probably wrong path in the esp

**Comment by erri120** [comment]
Fixed with 

[Forgotten Wenches.zip](https://github.com/erri120/lotus/files/4171950/Forgotten.Wenches.zip)

**Comment by erri120** [comment]
(re-appeared again due to changin TAWOBA)

**Comment by ghost** [comment]
Took a look at the ESP in xEdit. All the references to Falmer bikinis are wrong. The path is correct but virtually all filenames have changed and there's no consistency. I did what I could with the "Armors" category (ground meshes). If this looks good to you I'll continue after busting a few (virtual) heads.
[caco's FW Bikini patch.zip](https://github.com/erri120/lotus/files/4209088/caco.s.FW.Bikini.patch.zip)
