### ISSUE TITLE
CTD in lock picking interface

### ISSUE THREAD

**Issue by pgdeaner** [erri120/lotus#104]
![ScreenShot198](https://user-images.githubusercontent.com/11461193/82556183-7a3b7180-9b26-11ea-91d8-162c5db37063.png)
[Crash_2020_5_20_19-57-31.txt](https://github.com/erri120/lotus/files/4662262/Crash_2020_5_20_19-57-31.txt)

**Describe the bug**
Tried to lockpick a chest and crashed to desktop.

**To Reproduce**
1. Go to chest in the abandoned bandit camp
2. Do try to open the chest

**Expected behavior**
chance to open the chest

**Screenshots**
added a screenshot of the chest in question.  Did not happen the second time I tried.

**Modlist version**
0.3.3 B
**Did you add any additional mods?**
Come together N Out of the way - Nausicaa's Tweaker
**Save file**
In some cases it's useful to upload and link a save file so I can quickly jump into the game and check the bug. You don't need to do this in most cases but problems with quests or scripts can be better debugged with a save file before it happened.

**Comment by erri120** [comment]
The crash log doesn't really point to a lock picking problem. While lock picking, the game continues running and the log points to a problem with enemy variations/immersive wenches

**Comment by pgdeaner** [comment]
Fair enough.  Trying to pick that lock does cause a bandit spawn at that camp.  I would suppose it's connected to that then?

**Comment by zhongjiedong** [comment]
> 
> 
> Fair enough. Trying to pick that lock does cause a bandit spawn at that camp. I would suppose it's connected to that then?

Possibly, is it consistent ctd or just happened once? I've had a wench crash me when fighting a dragon before with a similar crash log referring to spells used. Once I reloaded she got replaced by a different wench and then no crashing.

**Comment by pgdeaner** [comment]
It was not consistent.  Good chance that it is connected to the NPC generation.
