### ISSUE TITLE
Unusual mist effect in Helgen cave

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#12]
The mist effect above the water next to Ralof (prone) disappears in the periphery.

1. Enter the Helgen Keep cave as directed by LAL.
2. Go to the area where Ralof is lying by the cart
3. Adjust the camera in first person until you see the bug

**Expected behavior**
The mist should remain :)

Remembered the console this time
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 02 14 - 23 39 41 17](https://user-images.githubusercontent.com/60791468/74581954-dc169900-4f83-11ea-96d5-83b9f66597b9.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 02 14 - 23 40 10 53](https://user-images.githubusercontent.com/60791468/74581955-e173e380-4f83-11ea-9258-ba714cf8a014.png)

**Comment by ghost** [comment]
Could be related to quick light like the flickering that appeared later. Will test shortly.

**Comment by ghost** [comment]
Problem is evident with or without quick light.

**Comment by erri120** [comment]
Should be fixed in the next update
