### ISSUE TITLE
Floating X activator in Breezehome

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#13]
**Describe the bug**
When spawning into Breezehome via LAL, red transparent X floating in the middle of the bedroom door.

**To Reproduce**
1. Choose alternate start, own Breezehome.
2. Look around :)

**Expected behavior**
No red X. Little console work and Google tells me this is an activator for the Shrine to Clavicus Vile.

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 02 15 - 00 06 54 49](https://user-images.githubusercontent.com/60791468/74582386-0454c680-4f89-11ea-9b18-ea61aebda684.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 02 15 - 00 07 46 35](https://user-images.githubusercontent.com/60791468/74582408-441bae00-4f89-11ea-9410-78bb7214e1a8.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 02 15 - 00 09 14 32](https://user-images.githubusercontent.com/60791468/74582409-48e06200-4f89-11ea-9603-0c32e7577e4d.png)

**Comment by erri120** [comment]
Fixed in the next update
