### ISSUE TITLE
Defeat + AGO Bleeding = Stuck

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#15]
**Describe the bug**
AGO bleeding doesn't play well with Defeat surrender. I was rolling with a full Riverwood party (Faendal, Gorr, and Hjorlmir (sp)) and cleaning up the watchtower near Bleak Falls. Decided to surrender for kicks but the aggressor had an arrow in his back. He died before the SL animation could start and I was stuck standing. Resetting Defeat would probably solve this but I didn't want to risk it.

**To Reproduce**
1. Surrender to an enemy with an arrow in his back (good luck)

**Expected behavior**
Ideally Defeat would recognize bleeding and end its sequence but thats unlikely. Disable bleeding might work.

**Screenshots**
N/A

**Comment by erri120** [comment]
Maybe fixed in the next update. I changed the AGO Bleeding effect to stop at 30% HP instead of 10%.
