### ISSUE TITLE
Physics crash tanked FPS

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#16]
**Describe the bug**
In the middle of combat at Bleak Falls exterior, looted a female bandit of all gear. Breasts stretched to infinity and framerate tanked to the single digits for the rest of combat. Managed to clear them out, but fps didn't rise above 30 after reloading a previous save. Only way to restore normal function was to restart Skyrim.

**To Reproduce**
Doubt it's reproducible. If SMP is on more than one actor it'll happen eventually.

**Expected behavior**
Breasts are naturally finite in size. :)

**Screenshots**
The corpse disappeared before I could locate it after combat.

**Comment by ghost** [comment]
This time it was combat at the Traitor's Post near the Boethiah statue. I was attempting to be sneaky at level 1 despite being extremely outnumbered, and should probably have AddItem'ed in some better gear. After a couple of deaths and reloads the fps tanked to the single digits and wouldn't improve until Skyrim was restarted. This happened once more after a relaunch of Skyrim. Third time's a charm, I'm going to AddItem in some DX gear and if I still can't beat these guys move on to another alternate start location.

**Comment by ghost** [comment]
Here's a screenshot of the possible cause. Something about the belly physics. Looks this way with or without armor until Skyrim is restarted.
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 02 17 - 21 40 38 39](https://user-images.githubusercontent.com/60791468/74699331-681c0100-51ce-11ea-9aae-98e556cf3db4.png)

**Comment by erri120** [comment]
Closed for now
