### ISSUE TITLE
Brown face NPC in whiterun

### ISSUE THREAD

**Issue by hambonee69** [erri120/lotus#19]
**Describe the bug**
One of the NPCs in whiterun has a brown face bug

**To Reproduce**
Just find the NPC

**Expected behavior**
Can it be corrected?

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from this mod: https://www.nexusmods.com/skyrimspecialedition/mods/30907.
![ScreenShot45](https://user-images.githubusercontent.com/61093726/74593841-727aa700-4fe4-11ea-8abe-c0cb8f13bb68.png)

**Comment by erri120** [comment]
Fixed
