### ISSUE TITLE
CTD in whiterun near well

### ISSUE THREAD

**Issue by hambonee69** [erri120/lotus#20]
**Describe the bug**
Talking to NPCs near the well in Whiterun seems to pretty constantly cause a CTD

**To Reproduce**
This is how I did it.
1)Choose to spawn a new character owning property in Riften
2)Exit riften and ride carriage to Whiterun stables
3)Enter front gates and head towards well
4)Start talking to the NPCs around the well near the tavern. I pretty much instantly CTD here.

**Expected behavior**
Correct the CTD with this

**Screenshots**
This is a screen shot right before the CTD. I clicked A on this NPC and crashed but I have done it with others.
![ScreenShot45](https://user-images.githubusercontent.com/61093726/74593890-1ebc8d80-4fe5-11ea-920e-32483bb20d98.png)

**Comment by erri120** [comment]
Fixed
