### ISSUE TITLE
Script lag starting scenes in Sleeping Giant Inn

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#22]
**Describe the bug**
First the SexLab scene took about 10 - 15 seconds to start, then when it did, no animation played and the two actors occupied the same position, clipping through each other. 

**To Reproduce**
1. Complete Camilla Valerius' Amorous Adventures quest.
2. Come back at a later time to request a scene while she is visiting the inn with several patrons
3. Request a lover's touch
4. Answer no to dominate female
5. Answer yes to use nearby bed
6. See above

**Expected behavior**
SexLab scene that starts within 5 seconds and plays properly.

**Screenshot**
I have one but unsure if it's appropriate for a public git.

**Comment by erri120** [comment]
Could not replicated on 0.2.0
