### ISSUE TITLE
Mismatched NPC Textures/Body

### ISSUE THREAD

**Issue by Dracosaber** [erri120/lotus#25]
**Describe the bug**
Many female NPCs have very noticable neck/wrist/ankle seams and mismatching textures between those parts. Some NPCs, such as Serana, have very noticable mismatching textures on the entire body. Unsure how many others may be affected.

**To Reproduce**
Can see on many NPCs, most notably those affected by the Bijin series of mods from what I could find. Nude Serana was the most obvious.

**Expected behavior**
No such seams or texture issues.

**Screenshots**
![ScreenShot47](https://user-images.githubusercontent.com/61095759/74611591-3c642280-50cb-11ea-8c05-c68bb93982a6.png)

**Comment by erri120** [comment]
Should be fixed by now
