### ISSUE TITLE
Bodyslide conversions; Minidress Collection.

### ISSUE THREAD

**Issue by nahm8y** [erri120/lotus#29]
**Request**
I converted the Minidress Collection to 3bbb along with using the Uniboob reference, here's the link:
https://mega.nz/#F!yHYx3YaC!X5U5SYgDtt4GPTunjI-PTw

**Additional context**
If there are any issues then send them my way and I'll be happy to fix them.  Wench clothes and Temple Priest clothes weren't converted using the reference, just converted to 3bbb as I felt they didn't need the former.  I plan to do more at some point along with splitting the different clothes types into separate groups, E.G. Nude/Clothed/Armoured/Cleavage as that fits the use of multiple bodyslides at once.

**Comment by erri120** [comment]
new link: https://mega.nz/#!rOAExQTa!7j72ccNTtSa6WM4W0Y0-blHNiEpLU80cbzAai6MF1GE

**Comment by erri120** [comment]
Added in 0.2.0
