### ISSUE TITLE
Problem with seams on Bijin characters, fix included.

### ISSUE THREAD

**Issue by nahm8y** [erri120/lotus#30]
**Describe the bug**
Hand seams on Bijin Characters after building bodyslide (Possibly beforehand but I haven't played without building one).

**To Reproduce**
1. Build Bodyslide.
2. See hand seams.
3. Be disappointed.

**Expected behavior**
Seamless hands.

**Fix**
Problem is fixed with the following Bijin Bodyslide mod: https://www.nexusmods.com/skyrimspecialedition/mods/16097

**Comment by erri120** [comment]
ty, added the mod and fixed the bug.
