### ISSUE TITLE
Captured wolf in BESS has same missing part issue as horse prior

### ISSUE THREAD

**Issue by hambonee69** [erri120/lotus#31]
![wolf](https://user-images.githubusercontent.com/61093726/74753785-7d704a00-5225-11ea-9e3e-48e4bec0280b.jpg)
**Describe the bug**
The captured wolf in BESS is also missing the penis

**To Reproduce**
Follow quest to this point
ENter Cage
Anim starts
it's missing...

**Expected behavior**
Fix missing part

**Screenshots**

**Comment by hambonee69** [comment]
horse and dog work though.

**Comment by erri120** [comment]
The Bestial Essence mod is kinda funny, I just played through the entire questline and did not encounter any bugs, the no slong bug was only caused if the actor was already spawned and I reloaded meaning that it should work the first time around. I have no idea why it wouldn't work after reloading...
