### ISSUE TITLE
Include Hentai Creatures

### ISSUE THREAD

**Issue by Bibbley** [erri120/lotus#33]
Hentai Creatures adds spells that allow the spawning of female creatures (which there appears to be no way to do currently). Which is nice if you play a male character.

I have tested the HentaiCreatures_MNCv12SE2 file available on the LL SSE MNC page since 0.1 and have had no issues

I See no incompatibilities in xEdit and havent experienced issues testing it on my own machine

I also added these anims from LE (converted over with cathedral asset optimizer) and the only issues ive experienced are broken facial expression on a few creatures in some animations (most worked fine)

https://www.loverslab.com/files/file/2702-funnybizness-v25-slal-pack-by-shashankie/

**Comment by erri120** [comment]
Closed for now
