### ISSUE TITLE
[Minor bug] [Landscape conflict] Thief added structure is overlapping LoTD musem entrance gate   

### ISSUE THREAD

**Issue by kociara81** [erri120/lotus#38]
**Describe the bug**
So while I'm was done some playtesting and wanted to visit The Dragonborn museum in Solitude, some random walls, plants and tree added by Thief mod are blocking entrance gate for museum. I'm used temporary fix with using disable command

**To Reproduce**
1. Go to Solitude
2. Get near LoTD's museum entrance gate

**Expected behavior**
Some random things shouldn't block the entrance gate to museum.

**Modlist version**
v0.2.1

**Did you add any additional mods?**
No

**Comment by erri120** [comment]
should be fixed in 0.2.2
