### ISSUE TITLE
Nara and Lokir

### ISSUE THREAD

**Issue by Bibbley** [erri120/lotus#39]
2.1

Nara and Lokir

Dark Elf and Nord

By Tardigraded

![Nara](https://user-images.githubusercontent.com/61074764/76031383-32c92000-5efd-11ea-89c8-93106caa20c3.png)
![Nara Body](https://user-images.githubusercontent.com/61074764/76031407-3bb9f180-5efd-11ea-8d6b-c6cda8a86bcd.png)
![Lokir](https://user-images.githubusercontent.com/61074764/76031413-407ea580-5efd-11ea-9dc1-179c75c911f0.png)
![Lokir (2)](https://user-images.githubusercontent.com/61074764/76031418-42486900-5efd-11ea-8176-7251f7876767.png)

Made only with lotus (Skin texture is bijinn for Nara and 2b bodyslide preset with some tweaks done in Racemenu)

https://www.nexusmods.com/skyrimspecialedition/mods/31101

**Comment by Bibbley** [comment]
[Tardigraded Presets.zip](https://github.com/erri120/lotus/files/4332252/Tardigraded.Presets.zip)

Forgot to actually include the preset!

**Comment by erri120** [comment]
Closed for now
