### ISSUE TITLE
Unable to download Sexlab Approach and FreeFlyCam

### ISSUE THREAD

**Issue by ApocryphalWord** [erri120/lotus#44]
**Describe the bug**
When installing, I run into an error "Unable to download" "Sexlab Approach Redux 1.25 English SE.7z" and "FreeflyCamSKSE64_v12.1 (1.5.73-97).zip"

If I look in the download folder I do have these files, so I'm guessing they've been updated?  Not sure if you take issues for that.

**To Reproduce**
Load the lotus modlist into wabbajack, attempt to install

**Expected behavior**
The install completes successfully

**Modlist version**
0.2.2

**Did you add any additional mods?**
No

**Comment by erri120** [comment]
Wait for update
