### ISSUE TITLE
downloads fail at start

### ISSUE THREAD

**Issue by LordKael9** [erri120/lotus#50]
the download from wabbajack does not start

**To Reproduce**
simply start the download

**Expected behavior**
error in the first download

**Screenshots**
0,45 - Wabbajack Build - 22a307844b68dbb27fbbb3e65495f8c52cbc4397
0,48 - Detected Windows Version: 6.2.9200.0
0,48 - System settings - (15,9GB RAM), Display: 1920 x 1080 (3,9GB VRAM - VideoMemorySizeMb=10240)
1,01 - Wabbajack Version: 1.1.5.0
5,91 - Starting to install Lotus 0.2.2 (BETA)
5,98 - Benchmarking C:\Users\LK9-Net\Desktop\Lotus
9,31 - 713,4MB/sec for C:\Users\LK9-Net\Desktop\Lotus
9,31 - Recommending a queue size of 4 based on disk performance, number of cores, and 15,9GB of system RAM
9,31 - Cleaning VFS, this may take a bit of time
9,37 - cmd.exe (7976) StdErr: Impossibile trovare C:\Users\LK9-Net\Desktop\Lotus\vfs_staging
9,37 - cmd.exe (7976) StdErr: Impossibile trovare il file specificato.
9,38 - Total number of Steam Libraries found: 0
9,39 - Searching for Steam Games in g:/program files/steam\steamapps
9,39 - Steam Game "Steamworks Common Redistributables" (228980) is not supported, skipping
9,39 - Steam Game "Space Engineers" (244850) is not supported, skipping
9,39 - Steam Game "No Man's Sky" (275850) is not supported, skipping
9,39 - Steam Game "Osiris: New Dawn" (402710) is not supported, skipping
9,39 - Found Steam Game: "The Elder Scrolls V: Skyrim Special Edition" (489830) at g:/program files/steam\steamapps\common\Skyrim Special Edition
9,39 - Found Steam Game: "The Elder Scrolls V: Skyrim" (72850) at g:/program files/steam\steamapps\common\Skyrim
9,4 - Total number of Steam Games found: 2
9,4 - Wabbajack.Common.StoreHandlers.StoreException: Could not open the GOG registry key!
9,4 - Wabbajack.Common.StoreHandlers.StoreException: Could not Init the GOGHandler, check previous error messages!
9,4 - Validating Game ESMs
9,4 - Validating Dawnguard.esm
9,55 - Validating Dragonborn.esm
9,84 - Validating HearthFires.esm
9,85 - Validating Update.esm
9,91 - Validating Modlist
9,91 - Loading server whitelist
10,08 - Loaded permissions for 115 servers and 50 Google Drive files
10,08 - Running validation checks
10,36 - Schlongs_of_Skyrim_SE_HDT-SMP - v1.1.rar is not a whitelisted download
10,37 - 0.95.57.eng.rar is not a whitelisted download
10,37 - Sexlab Defeat Addon by BakaFactory 1.01V SE English.7z is not a whitelisted download
10,41 - Encountered error, can't continue - System.Exception: 3 validation errors found, cannot continue.
   at Wabbajack.Lib.Validation.ValidateModlist.RunValidation(WorkQueue queue, ModList modlist) in T:\test-agent\_work\1\s\Wabbajack.Lib\Validation\ValidateModlist.cs:line 60
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Installer.cs:line 85
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__49_0() in T:\test-agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 172
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 159
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 366

**Comment by baggboy** [comment]
Yes, this is due to the list currently being down. It should be back up soon.
