### ISSUE TITLE
jBS2BG

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#52]
https://www.loverslab.com/topic/90812-jbs2bg-bodyslide-to-bodygen-convertergenerator/

The gist is you assign bodyslide presets to a pair of ini files that generates RaceMenu morphs that are applied to a base body by an SKSE script each time an NPC is encountered. A detailed guide is featured above which I encourage you to read, but the summation can be found in these three screenshots.

![image](https://user-images.githubusercontent.com/60791468/79024729-d8515e00-7b51-11ea-9631-6979105bc1fe.png)

Here we see my custom 3BBB preset at the top, along with all of the presets from "CBBE Presets Compendium" available on the Nexus. Frostdry, maniac that he is, has 31 xmls with groups of BodySlide presets available for you to choose from. This is his baby, he should get all the credit, I'm just doing a short writeup of how I got it working.

![image](https://user-images.githubusercontent.com/60791468/79024855-30886000-7b52-11ea-8fee-12f8b0c3019a.png)

I'm lazy so this is me assigning every preset to all females. The plugin will choose one randomly for every nice lady in the game. Frostdry is busy making things like petite elves and muscular orcs. But I say this is the 90s and a man needs a little variety.

![image](https://user-images.githubusercontent.com/60791468/79024990-85c47180-7b52-11ea-9cf1-0c8ad598ffed.png)

Final step, you have to export your inis into these directories for each plugin that has an NPC record in it. Or not, if you want to exclude certain NPCs. Tested it and works fine, loaded the game several times and different folks had different bazombas each time. A last note, though, NPCs with custom femalebody nifs won't get morphed. Haven't figured out how to get around that, the two of us.

That's about it. I myself am using EBD (a detestable SkyProc patcher) to randomize body textures. If you're interested in that I can do another PR with info.

**Comment by erri120** [comment]
https://www.loverslab.com/topic/53531-unofficial-bodygen-docs/
