### ISSUE TITLE
Heads up about Maids II and 3DNPC interaction

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#55]
I believe this interaction was discussed in the channel with respect to my crashes from the brothel cell, but that appears to have been an error on my part (disabled the random encounters plugin without ensuring it was also disabled in the Maids II MCM).

However I have encountered the known issue below and applied the recommended fix, which has NOT been implemented yet in the "official" Maids II - 3DNPC compatibility patch. I can confirm that the CTD occurs every time climbing the mountain east of Riften, and never after the fix has been applied. Link below for your reference.

https://forums.nexusmods.com/index.php?/topic/5174590-maids-ii-deception-patches-and-miscellaneous/page-5#entry78185983

**Comment by NotTotal** [comment]
3DNPC nexus posted a maids deception patch on its page, might be worth checking out [https://www.nexusmods.com/skyrimspecialedition/mods/29194?tab=files](https://www.nexusmods.com/skyrimspecialedition/mods/29194?tab=files)

**Comment by erri120** [comment]
Added the patch
