### ISSUE TITLE
wabbajack gives whitelist error

### ISSUE THREAD

**Issue by toguspyder** [erri120/lotus#56]
When trying to download from Wabbajack, it gives a whitelist error. I have included the log incase I have misinterpreted it wrong.

2.43 - Wabbajack Build - 22a307844b68dbb27fbbb3e65495f8c52cbc4397
2.55 - Detected Windows Version: 6.2.9200.0
2.55 - System settings - (15.9GB RAM), Display: 1920 x 1080 (1.9GB VRAM - VideoMemorySizeMb=10240)
3.23 - Wabbajack Version: 1.1.5.0
47.89 - Starting to install Lotus 0.2.2 (BETA)
48.05 - Benchmarking D:\Lotus\Lotus
50.4 - 901.8MB/sec for D:\Lotus\Lotus
50.41 - Recommending a queue size of 6 based on disk performance, number of cores, and 15.9GB of system RAM
50.42 - Cleaning VFS, this may take a bit of time
50.45 - cmd.exe (11572) StdErr: Could Not Find D:\Lotus\Lotus\vfs_staging
50.46 - Total number of Steam Libraries found: 0
50.47 - cmd.exe (11572) StdErr: The system cannot find the file specified.
50.47 - Searching for Steam Games in d:/games/steam\steamapps
50.49 - Steam Game "Steamworks Common Redistributables" (228980) is not supported, skipping
50.49 - Found Steam Game: "The Elder Scrolls V: Skyrim Special Edition" (489830) at d:/games/steam\steamapps\common\Skyrim Special Edition
50.5 - Total number of Steam Games found: 1
50.51 - Wabbajack.Common.StoreHandlers.StoreException: Could not open the GOG registry key!
50.51 - Wabbajack.Common.StoreHandlers.StoreException: Could not Init the GOGHandler, check previous error messages!
50.52 - Validating Game ESMs
50.54 - Validating Dawnguard.esm
50.71 - Validating Dragonborn.esm
50.94 - Validating HearthFires.esm
50.96 - Validating Update.esm
51.02 - Validating Modlist
51.03 - Loading server whitelist
51.6 - Loaded permissions for 121 servers and 54 Google Drive files
51.61 - Running validation checks
51.82 - Schlongs_of_Skyrim_SE_HDT-SMP - v1.1.rar is not a whitelisted download
51.83 - 0.95.57.eng.rar is not a whitelisted download
51.84 - Sexlab Defeat Addon by BakaFactory 1.01V SE English.7z is not a whitelisted download
52.03 - Encountered error, can't continue - System.Exception: 3 validation errors found, cannot continue.
   at Wabbajack.Lib.Validation.ValidateModlist.RunValidation(WorkQueue queue, ModList modlist) in T:\test-agent\_work\1\s\Wabbajack.Lib\Validation\ValidateModlist.cs:line 60
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Installer.cs:line 85
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__49_0() in T:\test-agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 172
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 159
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 366

**Comment by baggboy** [comment]
Please... just do the smallest amount of research. Lotus is currently down and should be back up soon.

**Comment by toguspyder** [comment]
Baggboy,

Sorry, there was nothing in the write up about that under the project and nothing in the issues. 

Where was this stated at? I came across the github download via google search. Was this posted somewhere else?

**Comment by baggboy** [comment]
It’s all good. Are you not in the Wabbajack discord? All answers to pretty much anything will be in there. Just make sure to join the NSFW channel.

**Comment by toguspyder** [comment]
Didn't even think about looking in the discord since it was not a mod list under Wabbajack, but I am part of it. Just started playing with Wabbajack last week. 

Thanks for the direction, I'll head over there to see what to dig up.
