### ISSUE TITLE
Corrupted modlist

### ISSUE THREAD

**Issue by Kiaos** [erri120/lotus#57]
**Describe the bug**
When opening the Lotus wabbajack modlists it says corrupted modlist and does not respond.

**To Reproduce**
1. download release of lotus 
2. install wabbajack 
3. Select install from from disk
3. select lotus wabbajack file

**Expected behavior**
Lotus would install correctly.
![image](https://user-images.githubusercontent.com/32118932/80819036-79e83000-8b91-11ea-8e39-404242b14047.png)

**Comment by Kiaos** [comment]
there is no other issue that has been closed im stuck I updated to lattest wabbajack and its broken

**Comment by baggboy** [comment]
Yeah... the list is down.. An update for it will be out on May 5th.
