### ISSUE TITLE
Nemesis PCEA conflicts with Devious Devices animations

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#58]
**Describe the bug**
Many devices change player animations when equipped. Since they do not default to the PCEA virtual directory, they are not applied to the player. For this reason, devices such as armbinders and yokes will not function as the bondage dominatrixes intended.

**To Reproduce**
1. Activate the Mara statue and select the captured princess / slave start.
2. The player's arms will not go into the armbinder / elbowbinder.

**Expected behavior**
Bind me tight, Mistress Kimy.

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 05 - 10 09 31 55](https://user-images.githubusercontent.com/60791468/81075618-98636980-8eb8-11ea-8963-b0ff71643e5e.png)

**Modlist version**
0.3

**Did you add any additional mods?**
No.

**Comment by ghost** [comment]
After a bit more research, it appears my initial diagnosis of the problem was not exactly accurate. When only the armbinder is equipped, the idle animation is correct, like so:

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 05 - 16 42 39 87](https://user-images.githubusercontent.com/60791468/81114288-c021f400-8eef-11ea-8c04-410a9bbdebca.png)

But when the hobble dress is added as in the "slave" scenario, the arms escape the armbinder, like this:

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 05 - 16 43 05 04](https://user-images.githubusercontent.com/60791468/81114333-d6c84b00-8eef-11ea-85c3-1ff12c2991ae.png)

I still suspect it has something to do with PCEA or DAR, as you mentioned, because I have neither mod in my DCUR test setup and all the devious idle animations function as desired.

**Comment by erri120** [comment]
Prob PCEA. I think we can create a DAR mod that will use the DD anims with special conditions since they take presence over PCEA

**Comment by harrythehamster** [comment]
I have the same bug, starting as enslaved princess

**Comment by canyoupicturethat** [comment]
Same as harrythehamster. In a non-princess playthrough, when having a follower bind me, the armbinder worked correctly.
