### ISSUE TITLE
Devious Devices physics on some devices still bugged.

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#60]
**Describe the bug**
You probably already know DD still has bugs, but the chains float in mid-air on the "iron chain harness." 

**To Reproduce**
Go through the "Chloe" quest and get the harness from her, or console them in and wear them. You will see the chains floating around as you move. For the record I did switch on and off the SMP object on both myself and Chloe with no effect.

**Expected behavior**
Dangly chains.

**Screenshots**
Not a very good shot but here it is. The chain is to the lower right of the hooded character. 

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 05 - 19 35 31 09](https://user-images.githubusercontent.com/60791468/81129609-df7e4880-8f12-11ea-8d31-41a07024d4bd.png)

**Modlist version**
0.3

**Did you add any additional mods?**
No.

**Comment by erri120** [comment]
![ScreenShot194](https://user-images.githubusercontent.com/16577545/81170120-a46b2c00-8f89-11ea-8a65-adadf2269b9c.png)

**Comment by erri120** [comment]
Fixed in the next update
