### ISSUE TITLE
Confusion about Cursed Loot

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#61]
**Describe the bug**
Not really a bug, more of a report on the way Cursed Loot is being misunderstood by Lotus players. Several players have followed the MCM's instructions to load the preset without considering what it does in terms of gameplay. They mostly expressed frustration at how they were rendered helpless so frequently. One person even tried to use it with a male character and didn't understand why his torso turned invisible. Perhaps more elaboration in the readme would be helpful.

**Comment by baggboy** [comment]
iirc erri insists in the readme at the cursed loot part that you need to read the mods description

**Comment by ghost** [comment]
Oh, okay, people just aren't following instructions then. I'll close this issue and keep it in mind for future questions. I actually forgot about it myself, but I'm already too familiar with Cursed Loot for my own good.
