### ISSUE TITLE
GK Follower Lack of Physics

### ISSUE THREAD

**Issue by ForgottenGlory** [erri120/lotus#62]
**Describe the bug**
Followers from the GK lineup do not have physics.

**To Reproduce**
Easiest one is Lydia:
1. Get Lydia as a follower.
2. Put her in an outfit that should have physics.
3. Observe lack of physics.

**Expected behavior**
Physics to be applied.

**Screenshots**
https://discordapp.com/channels/694274240786202694/699924123954053170/707465685588246529

**Modlist version**
0.3.0

**Did you add any additional mods?**
No.

This can be fixed by copying the skeleton_female.nif file from the "meshes\actors\character\character assets female" folder in the XP32 Maximum Skeleton Special Extended mod into the "Meshes\actors\character\GKFollower" folder for the GK Follower Core File SE CBBE mod per the Warning.txt file included with GK Follower Core File SE CBBE mod. I have tested this myself and it corrects the issue.

**Comment by erri120** [comment]
Fixed in the next release
