### ISSUE TITLE
Footwear does not make the correct AOS sound effects at "jog" movement speed.

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#63]
**Describe the bug**
I have encountered this on my own builds. When using AOS in conjunction with Footstep Sets from other mods such as ISC or TUDM, Smash jams them together in an invalid configuration that results in no sound when moving at normal "jog" speed (as opposed to "walk" or "sprint.")

**To Reproduce**
1. Put on a set of light boots.
2. Walk around on standard ground.
3. Experience the silence.

**Expected behavior**
Luscious footsounds.

**Screenshots**
N/A (Not Applicable)

**Suggested resolution**
Either delete both "Footstep Set" entries from the "Smashed Patch" or forward the records from a previous mod into the Smash Override.

**Modlist version**
0.3

**Did you add any additional mods?**
No

**Comment by erri120** [comment]
Fixed in the next update
