### ISSUE TITLE
Request: Minineeds

### ISSUE THREAD

**Issue by Kukoro** [erri120/lotus#64]
**Request**
https://www.loverslab.com/files/file/4931-mini-sse-needs/

Mini SSE Need
This mod adds a set of needs to the player.
For each need, you can define how much time you can spend without satisfying the need. If too much time will pass some penalties will be applied.
You can also define the maximum percentage of the damage applied when a need is not satisfied.

**Comment by erri120** [comment]
This modlist will never feature any needs mods.
