### ISSUE TITLE
Orc NPC "Ghorza" has BFB

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#65]
**Describe the bug**
I'm not sure where this NPC is as this was reported by a "user," but she's named "Ghorza" and the screenshot looks like Markarth? Anyway she has a BFB as shown below.

**To Reproduce**
1. Go to whereever she is.
2. Bask in the bigotry.

**Expected behavior**
Correct orc skin tone

**Screenshots**

![unknown](https://user-images.githubusercontent.com/60791468/81177786-3452ab00-8f75-11ea-8f1e-290375a754a7.png)

![unknown2](https://user-images.githubusercontent.com/60791468/81177836-4d5b5c00-8f75-11ea-9e8e-9b6bbd19ed52.png)

![unknown3](https://user-images.githubusercontent.com/60791468/81177897-606e2c00-8f75-11ea-9f34-4a117f6a4e58.png)

** Suggested resolution**
Ghorza looked correct with a placeatme in the ASLAL cell after I deleted these two files...

![unknown4](https://user-images.githubusercontent.com/60791468/81178046-9c08f600-8f75-11ea-9493-471c6325f46b.png)

**Modlist version**
0.3

**Did you add any additional mods?**
No.

**Comment by Kukoro** [comment]
Npc is located in  Markarth
![image](https://user-images.githubusercontent.com/19671583/81179140-89a8af80-8fa9-11ea-8685-fe4deebbdc83.png)

**Comment by erri120** [comment]
Fixed in the next update
