### ISSUE TITLE
Enemy Variations BFBs

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#66]
**Describe the bug**
Some of them seem to have BFBs. Seems to be random. So far, I've seen them on WoodElfRace and OrcRace. Tsuki uses the mod extensively, perhaps you two can compare notes.

**To Reproduce**
Unfortunately there is no guaranteed way to reproduce it. You just have to fight bandits until one shows up. Attached is a screenshot of one instance.

**Expected behavior**
No BFBs.

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 06 - 09 24 37 69](https://user-images.githubusercontent.com/60791468/81184444-6b798a00-8f7e-11ea-9122-93f4999e2274.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 05 06 - 09 25 02 95](https://user-images.githubusercontent.com/60791468/81184480-73d1c500-8f7e-11ea-820e-ab94da093c2e.png)

**Modlist version**
0.3

**Did you add any additional mods?**
No.

**Comment by zhongjiedong** [comment]
![ScreenShot87](https://user-images.githubusercontent.com/20669755/81191576-130fb000-8fb1-11ea-90e4-428608cdc8dd.png)


exporting in CK fixes everything except draugr wood elves for some reason.

**Comment by erri120** [comment]
Fixed in the next update. As discussed on discord: the BSA version of EVW is missing 1800+ facegenom meshes

**Comment by erri120** [comment]
For more info https://forums.nexusmods.com/index.php?/topic/7354581-enemy-variations-v4-wenches/page-46#entry80535568
