### ISSUE TITLE
Delicate Face Presets broken

### ISSUE THREAD

**Issue by Kussie** [erri120/lotus#67]
**Describe the bug**
All of the Delicate face preset are various degrees of broken

**To Reproduce**
1. Start a new game
2. Change to female
3. Choose any of the delicate face presets

**Expected behavior**
A nice looking preset should appear

**Screenshots**
![ScreenShot202](https://user-images.githubusercontent.com/4960791/81235182-b0182a80-903d-11ea-848d-b76ac236433e.jpg)
![ScreenShot203](https://user-images.githubusercontent.com/4960791/81235189-b1e1ee00-903d-11ea-9e8b-69213ab7fda4.jpg)
![ScreenShot200](https://user-images.githubusercontent.com/4960791/81235190-b27a8480-903d-11ea-92dc-9369d0d36f62.jpg)
![ScreenShot201](https://user-images.githubusercontent.com/4960791/81235191-b3131b00-903d-11ea-98dc-110686959331.jpg)

**Modlist version**
3.0

**Comment by baggboy** [comment]
Check the change log for 3.1

**Comment by erri120** [comment]
Version 3.0 and 3.1 doesnt exist, removed in the next update
