### ISSUE TITLE
Issue with Eisen armour in Maids II - Deception not appearing correctly

### ISSUE THREAD

**Issue by Drikanyx** [erri120/lotus#68]
**Describe the bug**
When entering the Euphoria Palace warehouse during the mod's quest line, I noticed that the assassin's outfits were not being loaded correctly - see screenshots attached.
The boots appear to be missing meshes. 

**To Reproduce**
1. Progress in Maids II to the point where you can enter the Euphoria palace warehouse and have the assassins appear.
2. Examine assassins to see the missing meshes.

**Expected behavior**
I expected to see the boots' meshes and textures.

**Screenshots**
![ScreenShot195](https://user-images.githubusercontent.com/32592872/81250813-ca401180-9019-11ea-9097-4e6e5d31654b.png)
![ScreenShot194](https://user-images.githubusercontent.com/32592872/81250815-cb713e80-9019-11ea-9793-95ccd3b18144.png)
(ignore the junk in the console in the bottom image, I was searching for the name of the gear to troubleshoot but it's named differently in the mod files anyway)
**Modlist version**
0.3.0

**Did you add any additional mods?**
No.

**Save file**
 Attached save/skse which should be right at the point of issue.
[Saves.zip](https://github.com/erri120/lotus/files/4590547/Saves.zip)

**Comment by erri120** [comment]
![ScreenShot196](https://user-images.githubusercontent.com/16577545/81273555-92979080-903e-11ea-8108-1ad7ddc0282f.png)

**Comment by erri120** [comment]
![ScreenShot197](https://user-images.githubusercontent.com/16577545/81274407-c3c49080-903f-11ea-8951-6555f0a007d9.png)
[Maids II - Deception Mod Patches](https://www.nexusmods.com/skyrimspecialedition/mods/6288) changed the boots mesh in a bad way.
