### ISSUE TITLE
Corrupt modlist due to missing BakaFactory ABC LE SE 1.51V.7z

### ISSUE THREAD

**Issue by shazdeh** [erri120/lotus#69]
**Describe the bug**
Installation of modlist fails with an error, "Unable to download BakaFactory ABC LE SE 1.51V.7z".

**Screenshots**
![image](https://user-images.githubusercontent.com/854165/81270347-d8188580-905f-11ea-8141-ba94a816b588.png)

**Modlist version**
3.0

Thank you!

**Comment by erri120** [comment]
Version 3.0 doesnt exist, also fixed in the next update

**Comment by shazdeh** [comment]
Awesome, thanks! Any idea when the next update hits?
