### ISSUE TITLE
Severely limit DCUR, even when enabled

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#70]
**Request**
Reconfigure DCUR so that its options are even more circumscribed than they currently are because the "gameplay" primarily consists of clicking menus until you are freed. I mean you can walk around in bondage gear jiggling which is nice to look at but if you can't get out you will die or get caught in some Defeat bug since Defeat does not recognize Devious Devices. DCUR should be rare to get into and easy to get out of.

**Additional context**
I have attached my DCUR json which is a configuration similar to one I have been using for years. At least when I play with DCUR, which isn't that often. I do mention that I got a save out to 15 hours with this and it was pretty fun, but I must warn you that the prison overhaul system is buggy and doesn't always clear bounties when the sentence has been served, at least as of DCUR version 8.3. Also, it kinda defeats the purpose to be forced into nudity or public sex if you go to prison for it. Disabling public indecency and limiting prison time is all in this config. The only thing I would change is disabling Combat Surrender because wenches don't respect it. I doubt they would respect Defeat's passive flags either, though.

[DCURConfig.zip](https://github.com/erri120/lotus/files/4592748/DCURConfig.zip)

**Comment by erri120** [comment]
Updated config in the next release
