### ISSUE TITLE
Helgen dungeon bug

### ISSUE THREAD

**Issue by harrythehamster** [erri120/lotus#72]
**Describe the bug**
Upon reaching where the group of spider is, while trying to proceed through the dungeon, system detects a ignore collision behavior, then a warning shows up, afterward the player is teleported out in Helgen Keep.

**To Reproduce**
1. Go to Helgen dungeon
2. Do as said behavior in description

**Expected behavior**
player will be teleported out.

**Screenshots**
![image](https://user-images.githubusercontent.com/64973622/81311614-f8305f00-90c8-11ea-9e62-537445aa183a.png)

![image](https://user-images.githubusercontent.com/64973622/81313549-58280500-90cb-11ea-8447-99a8192f099b.png)

**Modlist version**
0.3.0
**Did you add any additional mods?**
No

**Save file**

**Comment by erri120** [comment]
Same as #59
