### ISSUE TITLE
In game time flow speed up bug

### ISSUE THREAD

**Issue by harrythehamster** [erri120/lotus#73]
**Describe the bug**
Following the missing texture in Helgen bug, I found my character to be incredibly fast, so are other NPCs. Not exactly sure what has caused it or how to reproduce it.

**Expected behavior**
In-game time is faster than normal.
Fix: Restart the game fixed the problem.

**Modlist version**
0.3.0
**Did you add any additional mods?**
No

**Comment by erri120** [comment]
Does it still happen with newer version?

**Comment by harrythehamster** [comment]
It never happened again, just that once, I suspect it might have something to do with bound feet (slower movement) and the game's attempt to restore normal movement speed. But if it ever happens to anyone, restarting the game is a simple fix.

**Comment by erri120** [comment]
Ill close this for now
