### ISSUE TITLE
Breast physics are all over the place.

### ISSUE THREAD

**Issue by NumberXer0** [erri120/lotus#75]
**Describe the bug**
Breasts freak out when walking. They become completely flat to the chest, even clipping inside the body slightly sometimes. When jumping, they stretch outwards and contort before going back to normal. They also seem to just constantly vibrate when standing still. I've tried various bodyslide presets. CBBE Slim, CBBE Curvy, ERF Succubus..even custom ones I made myself. They all do it. I'm running the included SE 3BBB Body Amazing and SMP is turned on with Num+. Is that not the correct setup?

**To Reproduce**
1. Take off clothing
2. Walk and jump

**Expected behavior**
I expected physics that behave normally

**Screenshots**
Here are the ERF Succcubus breasts. Much smaller than they should be. https://imgur.com/fd8BwjO
Here are how they look when you run. https://imgur.com/bq4XLTx

**Modlist version**
0.3
**Did you add any additional mods?**
No
**Save file**
Not needed

**Comment by NumberXer0** [comment]
I'd also like to add that they work fine under clothes, but not when nude. It seems to be an issue with the 3BBB body, as it doesn't do this with the basic CBBE body.

**Comment by erri120** [comment]
At what FPS are you running the game?

**Comment by NumberXer0** [comment]
60, with an occasional dip to 55ish in some areas.

**Comment by erri120** [comment]
SMP has problems with jumping and the 360 anims I use in Lotus. You can try changing the preset by re-installing CBBE 3BBB and choosing different presets for HDT and CBPC in the installer.
Problems when standing still come from havok and can be fixed by changing the SSE Display Fix config or just restarting.

**Comment by NumberXer0** [comment]
Alright, ill give that a shot. Thanks.

**Comment by erri120** [comment]
Actually I just noticed that I forgot to configure SSE Display Fix after I updated it...
Prob fixed in the next version, I close this for now
