### ISSUE TITLE
Nord: Blue Face during Scenes

### ISSUE THREAD

**Issue by NiceHacksDude** [erri120/lotus#76]
**Describe the bug**
During many different scenes, the faces on both the NPC and Player flash blue for a split second. Sadly I don't have the specific animation during the screenshot for which it was, yet during my testing, I found the majority of animations having this same issue. I suspect maybe this has to do when the scene activates blushing/face reactions. I have tried messing with some ENB settings to see if that was the issue, yet no success. I found a very old post with someone describing a similar problem (not related to lotus), yet they specify that it could be missing textures for the race. I really appreciate any help/guidance! 
Side Note: Right after the audio is triggered from either the Male or Female (Player or NPC) is when this issue occurs which is why I have reason to think it's related to blushing/aroused/face reactions.

**To Reproduce**
1. Character Nord - M + F (Nord)
2. Initiate Scene
3. It shouldn't matter which scene, almost all I've tested have this issue.
4. Watch face closely. 

**Expected behavior**
Face shouldn't appear blue.

**Screenshots**
https://i.imgur.com/JfnJG9s.png

**Modlist version**
0.3

**Did you add any additional mods?**
The only thing I did other than the instructions was fixing the Zaz_BodySlide_BreastRopeExtreme missing for body slide. I have since added MassMatchMaker and some animations yet this issue was apparent before adding the additional mods. 

**Save file**
Shouldn't be needed.

**Comment by ghost** [comment]
Writing to confirm this issue with self-satisfaction animations as a female redguard. Face flashes blue at the voiced intervals.

**Comment by NumberXer0** [comment]
I didn't have this issue myself on 0.3, but I've noticed it after updating to 0.3.2. Nord Female here and both my own and the males keep flashing. Its inconsistent it seems, as it doesn't always happen.
