### ISSUE TITLE
Bikini Armour Parts disappearing

### ISSUE THREAD

**Issue by J-Fri** [erri120/lotus#78]
**Describe the bug**
Parts of the bikini armour make other parts of the bikini armour set disappear, with equipping a top will make abs guards and tasset disappear.

**To Reproduce**
1. Equip Steel Bikini Armour Top IV, Steel Abs Guard III, and Steel Tasset I B, check model in 3rd person view, Abs Guard and Tasset should be invisible.
2. Unequip Top, check model in 3rd person view. Guard and Tasset should be visible (Tasset also clipping, unsure if that's my fault).

**Expected behavior**
Top shouldn't make other parts of the armour disappear, armour parts should be visible.

**Modlist version**
0.3

**Comment by SirDrake87** [comment]
I've had this issue before. It's an issue betwee SOS and Bikini Armor. Also could be an issue with Devious Devices and Bikini Armor

**Comment by ghost** [comment]
If it were devious it probably wouldn't matter what else you had equipped, the item just wouldn't show at all. The fact that one thing disappears when the other is worn suggests they share a slot. I think.

**Comment by SirDrake87** [comment]
> If it were devious it probably wouldn't matter what else you had equipped, the item just wouldn't show at all. The fact that one thing disappears when the other is worn suggests they share a slot. I think.

You are correct. You have to make sure the bikini top cannot be shlongified by SOS. You also have to go to devices underneath and set it to nothing (Something like that). When you do that, bam the extra stuff shows up. It's why I tend to not install bikini armor with DD/SOS installed. It's a pain.
