### ISSUE TITLE
Forward and idle animation broken when bound.

### ISSUE THREAD

**Issue by NumberXer0** [erri120/lotus#79]
**Describe the bug**
When standing still or walking forward while bound, the wrong animation plays. I did the captured princess start and was bound with a gag, armbinder, hobbledress and ballet shoes. While standing still or walking forward, my arms were in front of me and not in the armbinder. But while walking left and right they were properly in the armbinder.
After having the armbinder removed, my hands were stuck in a yoke animation. No yoke equipped, but they were up in the air while idle and moving forward. Again, moving left and right would play the proper animation.

**To Reproduce**
1. Start a new character with the Captured Princess start
2. Walk around after gaining control

**Expected behavior**
I expected the proper animations to play for the various Devious Devices

**Screenshots**
Not at my PC right now, but I can get some later. Its self explanatory though.

**Modlist version**
0.3
**Did you add any additional mods?**
No
**Save file**
Not at my PC

**Comment by erri120** [comment]
Same as #58
