### ISSUE TITLE
Add playerhome: The Grand Bathhouse SE

### ISSUE THREAD

**Issue by harrythehamster** [erri120/lotus#81]
**Request**
https://www.nexusmods.com/skyrimspecialedition/mods/7237/
This provides a convenient player home, with features:
-A manor
-Bath with your followers naked
-Fast travel to bathhouse/back to where you travelled from (so it wont break quest)
-All crafting stations in one room with item-sorting storages
-Rooms for followers/children
-An arena to watch customized fights
-A dragonsoul converter to perkpoints
-Has fishtank, toilet, shower, garden et
-Does not seem to get any updates so less likely to cause a problem for the modlist XD

**Additional context**
Never caused a bug for me although not guaranteed it won't cause problem for lotus, needs testing

**Comment by erri120** [comment]
Would require too many patches
