### ISSUE TITLE
Add Breezehome Mod

### ISSUE THREAD

**Issue by harrythehamster** [erri120/lotus#84]
**Request**
https://www.nexusmods.com/skyrimspecialedition/mods/2829
A beautiful looking overhaul of Breezehome
- All crafting stations
- Display for all daedric weapons, unique shields, staves, dragonpriest masks, dragonclaws etc.
- Tons of unique and custom labeled storage
- Lockable doors (Lock Lydia in her room!!)
- Bath tub and sauna
- Tons of custom and unique storage
- Mirror to change your appearance 

**Additional context**

**Comment by erri120** [comment]
That mod is ultra buggy.
