### ISSUE TITLE
Loot Overhaul - Rarity and Abundance (SkyRem - Lora) needs version update

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#86]
Loot Overhaul - Rarity and Abundance (SkyRem - Lora) 2.0.1 is not available on nexus current version available is 2.0.3 
Link - https://www.nexusmods.com/skyrimspecialedition/mods/26732/?tab=files

**Comment by erri120** [comment]
Already updated, see Changelog

**Comment by Aryan01111** [comment]
Changes:

    Updated SSE Display Tweaks to 0.3.14
    Updated Loot Overhaul - Rarity and Abundance (SkyRem - Lora) to 2.0.1

Version 2.0.1 is not available now current version is 2.0.3
