### ISSUE TITLE
After School [Skirt SMP][3BB] Outfit

### ISSUE THREAD

**Issue by ghost** [erri120/lotus#88]
**Request**
Can u add After School [Skirt SMP][3BB] 
https://www.loverslab.com/files/file/11629-after-school-skirt-smp3bb/
https://www.patreon.com/posts/after-school-smp-33460327

**Additional context**
A port of the punk-styled outfit designed by Melodic for SE.  Comes with bodyslide and 3 breast bone (3BB) support.  You must have a 3BB body (either CBBE SMP or 3BBB body) installed. Also comes with personally custom made SMP skirt physics.

Alt Link Given on Patreon
https://www.mediafire.com/file/9me1mj6avxtn6s1/%5BZynx%5D%5BMelodic%5D_After_School.7z/file

**Comment by erri120** [comment]
Nope
