### ISSUE TITLE
Character's Chest Disappears when choosing SMP Hair Option

### ISSUE THREAD

**Issue by Spanana576** [erri120/lotus#90]
In the character creation menu, if I chose one of the SMP Hair options, the chest and arms of my character fall into the ground.

**To Reproduce**
1. Create new female character or /showracemenu
2. Select an SMP Hair option, any of them

**Expected behavior**
As soon as you exit the character creation, my chest disappears. 

**Screenshots**

**Modlist version**
0.3.2 (but experienced this in previous versions) 

**Did you add any additional mods?**
Yes some follower mods, but experienced this without them as well. 

![ScreenShot204](https://user-images.githubusercontent.com/48873169/81601919-ae31cc80-9399-11ea-901a-0287ea218c19.png)

**Comment by erri120** [comment]
You forgot to build the Collision Shapes from KS Hairdos SMP for CBBE in BodySlide
