### ISSUE TITLE
Add M'rissi's tails of troubles and Konahrik's Accoutrements

### ISSUE THREAD

**Issue by GregariousJamie** [erri120/lotus#91]
Personally, i find M'rissi adorable and shes a great follower. Like look at that lil' gremlin and tell me you dont wanna protecc her. Quest is pretty cool too. 
https://www.nexusmods.com/skyrimspecialedition/mods/9666
Quest delay
https://www.nexusmods.com/skyrimspecialedition/mods/17810

Konahrik's Accoutrements is just a cool mod. Dragon preists are cool. More dragon priest stuff then obviously means skyrim as a whole is cooler. Furthermore it has stuff for the LOTD museum last i checked which is **very** awesome
https://www.nexusmods.com/skyrimspecialedition/mods/22206
Upscaled textures mod:
https://www.nexusmods.com/skyrimspecialedition/mods/34417

**Comment by erri120** [comment]
You can definitely forget Konahrik's Accoutrements
