### ISSUE TITLE
Add Carriage and Ferry Travel Overhaul

### ISSUE THREAD

**Issue by mael5trum** [erri120/lotus#94]
**Request**
There isn't a method to travel from Falkreath, Dawnstar and Morthal unless you have already been to where you want to go (fast travel).

**Additional context**
https://www.nexusmods.com/skyrimspecialedition/mods/8379
This mod adds more carriages and carriage stops as well as adds more ferries to use.

**Comment by NumberXer0** [comment]
+1. Great for people that use survival mode that disables fast travel.

**Comment by erri120** [comment]
Not feeling that mod
