### ISSUE TITLE
AIM FIX - total control over the crosshair for archery and magic

### ISSUE THREAD

**Issue by Kukoro** [erri120/lotus#96]
[https://www.nexusmods.com/skyrimspecialedition/mods/18524](https://www.nexusmods.com/skyrimspecialedition/mods/18524)

Makes aiming accurate out of the box. Provides total control over the crosshair position for archery and magic to match the hit point shift caused by the custom animations and mods.

----
If I change the axis of 3PCO my spells will not hit where the crosshair is. This mod fixes it. 
I tested it and it worked without any additional configuration (AIM FIX Lite)

**Comment by erri120** [comment]
That actually looks very good

**Comment by erri120** [comment]
Added in the next update
