### ISSUE TITLE
BeastRopeExtreme - Bodyslide

### ISSUE THREAD

**Issue by SirDrake87** [erri120/lotus#99]
**Describe the bug**
BeastRopeExtreme does not build properly in Bodyslide.

**To Reproduce**
1. Build bodyslide from 3.3
2. Profit

**Expected behavior**
Expected all outfits to build properly

**Screenshots**
![BeastRope](https://user-images.githubusercontent.com/65056112/82133469-25a89700-97b2-11ea-9b2b-0aae09db4337.PNG)

**Modlist version**
3.3

**Did you add any additional mods?**
No

**Comment by SirDrake87** [comment]
To fix this issue a guy already made a fix.
https://www.loverslab.com/topic/92119-breast-rope-extreme/?do=findComment&comment=2386626

**Comment by mael5trum** [comment]
The Fix is already included under the Others Separator labeled 'ZaZ BreastRopeExtreme fix' only it is not packaged properly.
It needs to be placed in the format \CalienteTools\BodySlide\ShapeData\BreastRopeExtreme\

**Comment by erri120** [comment]
Fixed in the next version
